[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "synceditor"
version = "0.1.0"

[dependencies]
anyhow = "1"
async-std = "1"
automerge = "0.5"
druid = "0.8"
futures = "0.3"
libp2p = { version = "0.52", features = ["full"] }
serde = "1"
serde_json = "1"
